### ISSUE TITLE
calling /users/martinei.json produces exception...

### ISSUE THREAD

**Issue by phaus** [innoq/githubble#1]
```
[info] play - Application started (Dev)
[error] application -

! @6j919oojn - Internal server error, for (GET) [/users/martinei.json] ->

play.api.Application$$anon$1: Execution exception[[JsResultException: JsResultException(errors:List((,List(ValidationError(error.expected.jsstring,WrappedArray())))))]]
    at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.3.jar:2.3.3]
    at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.3.jar:2.3.3]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [play_2.11-2.3.3.jar:2.3.3]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [play_2.11-2.3.3.jar:2.3.3]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.1.jar:na]
Caused by: play.api.libs.json.JsResultException: JsResultException(errors:List((,List(ValidationError(error.expected.jsstring,WrappedArray())))))
    at play.api.libs.json.JsValue$$anonfun$2.apply(JsValue.scala:67) ~[play-json_2.11-2.3.3.jar:2.3.3]
    at play.api.libs.json.JsValue$$anonfun$2.apply(JsValue.scala:67) ~[play-json_2.11-2.3.3.jar:2.3.3]
    at play.api.libs.json.JsResult$class.fold(JsResult.scala:77) ~[play-json_2.11-2.3.3.jar:2.3.3]
    at play.api.libs.json.JsError.fold(JsResult.scala:13) ~[play-json_2.11-2.3.3.jar:2.3.3]
    at play.api.libs.json.JsValue$class.as(JsValue.scala:65) ~[play-json_2.11-2.3.3.jar:2.3.3]
[error] application -

! @6j91a10db - Internal server error, for (GET) [/users/martinei.json] ->

play.api.Application$$anon$1: Execution exception[[JsResultException: JsResultException(errors:List((,List(ValidationError(error.expected.jsstring,WrappedArray())))))]]
    at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.3.jar:2.3.3]
    at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.3.jar:2.3.3]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [play_2.11-2.3.3.jar:2.3.3]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [play_2.11-2.3.3.jar:2.3.3]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.1.jar:na]
Caused by: play.api.libs.json.JsResultException: JsResultException(errors:List((,List(ValidationError(error.expected.jsstring,WrappedArray())))))
    at play.api.libs.json.JsValue$$anonfun$2.apply(JsValue.scala:67) ~[play-json_2.11-2.3.3.jar:2.3.3]
    at play.api.libs.json.JsValue$$anonfun$2.apply(JsValue.scala:67) ~[play-json_2.11-2.3.3.jar:2.3.3]
    at play.api.libs.json.JsResult$class.fold(JsResult.scala:77) ~[play-json_2.11-2.3.3.jar:2.3.3]
    at play.api.libs.json.JsError.fold(JsResult.scala:13) ~[play-json_2.11-2.3.3.jar:2.3.3]
    at play.api.libs.json.JsValue$class.as(JsValue.scala:65) ~[play-json_2.11-2.3.3.jar:2.3.3]
```

**Comment by martinei** [comment]
Works for me. Maybe github Quota reached? We shoud add error handling for that...

**Comment by phaus** [comment]
https://api.github.com/users/martinei works...

http://localhost:9000/users/martinei.json does also resolve in an error 500

**Comment by phaus** [comment]
[JsResultException: JsResultException(errors:List((,List(ValidationError(error.expected.jsstring,WrappedArray())))))]
In /Users/philipp/GIT/githubble/app/service/GitHub.scala:18

15  }

16

17  def embedd(attribute: String): Future[GitHubResource] = {

18    WS.url((json \ attribute).as[String]).get.map {

19      attributeContent =>

20        val transform = (**).json.update((** \ attribute).json.put(attributeContent.json))

21        GitHubResource(json.transform(transform).get)

22    }

23  }

**Comment by phaus** [comment]
/users/martinei.json != /users/martinei

**Comment by martinei** [comment]
Well. yes. There is no githubuser called "martinei.json".
